# fly.toml app configuration file generated for fss-tienda-fragrant-dream-1304 on 2024-02-08T12:47:54-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fss-tienda-fragrant-dream-1304'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 2048
